- sync/openwrt/operations.py
- sync/openwrt/system_manager.py
In the case when we are booting up with default settings, changes
made to /etc/config/system are not being set properly.  This is
because /etc/init.d/system runs before /etc/init.d/sync-settings.
When system_manager writes out startup scripts, also write out
zzz-reload-system, which includes a call to
/etc/init.d/system reload.  This will restart system if any changes
were made to /etc/config/system.  With zzz-reload-system, we don't
need to call /etc/init.d/system restart explicitly in operations.
MFW-801
> MFW-801: system_manager: Add zzz-reload-system

- sync/openwrt/system_manager.py
Use @ in sed script so it doesn't get confused by the / that may
be in the timezone definition.
MFW-844
MFW-843
MFW-842
> MFW-844-843-842: system_manager: Deal with timezone's with / in them

- sync/openwrt/network_manager.py
If an openvpn configuration file specifies 'persist-tun', remove it
before writing the file out.  That way, if the vpn connection goes
down, the tun interface is removed.  That enables us to correctly
reflect the status of the connection on the UI and in our wan routing
logic
MFW-847
> MFW-847: network_manager: openvpn: Suppress persist-tun in client configs

- sync/openwrt/network_manager.py
openwrt's ifdown/ifup commands operate on interfaces name (ie.
dogfood, expressvpn, etc) not device name (ie tun0).
MFW-797
> MFW-797: network_manager: Do ifdown/ifup on openvpn interface name

- sync/openwrt/network_manager.py
To test this fix, start with a MFW device/environment that does not have this fix. If you configure a static IPv6 address for one of the interfaces, and then look at the interface status at the command line (ifconfig), you'll see the address you configure does NOT get assigned to the interface. It is effectively ignored.
With this fix applied, static IPv6 addresses will be assigned to devices as expected.
Here are the detailed fix/commit notes:
I use static IPv6 networks/addresses in my development environment
and it seems we're doing the wrong thing in sync-settings with
the ip6addr and ip6prefix fields in /etc/config/network
According to the OpenWRT docs:
ip6addr = Assign given IPv6 address to this interface (CIDR notation)
ip6prefix = IPv6 prefix routed here for use on other interfaces …
> Fix ip6addr for static address and alias configs

- sync/debian/wireguard_manager.py
These changes depend on the changes made in the same branch name under ngfw_src.
> Fix sync-settings to work with the new wireguard data types

- sync/openwrt/network_manager.py
The validate_interface function in network_manager for MFW was throwing an exception for PPPoE interfaces. I looks like PPPOE simply wasn't included in the list of valid interface types. Adding to the array resolves the exception and allows settings to be saved normally.
> Fix interface validation for PPPoE configuration

- sync/openwrt/network_manager.py
We weren't writing the username, password, or DNS details into /etc/config/network which prevented PPPoE connections from working. This fix updates sync-settings to write the config entries for PPPoE interfaces.
> Mfw 1039 pppoe wan connection fixes

- sync/debian/wireless_manager.py
On upgrade to 15.1 we run sync-settings as part of the sync-settings
package postinst.  Customers with wireless interfaces that have not
made a network settings change post-14.2 will not have the
wirelessVisibility field defined in their network.js, which means
that the postinst sync-settings call will fail, which can cause
the upgrade to 15.1 to stall.  If wirelessVisibility isn't defined
for a wireless interface, just write out a 0.
NGFW-13205
> wireless_manager: Handle undefined wirelessVisibility

- sync/openwrt/network_manager.py
This fixes the wan routing rules for PPPOE connections, but I have a couple questions:
This logic replaces the interface name for a PPPOE interface in the nat-sys and interface-marks NFT tables from the logical interface to the PPPOE tunnel interface. Do we need to do something with the logical interface still? (I noticed some IPv6 ICMPv6 packets failing after making the change, but may not have been something serious).  Is there value in marking both the PPPOE tunnel as an interface and also the logical interface, or would this just be destroying the mark for the PPPOE tunnel traffic?
@jccoffin and I noticed the main routing table still gets populated with the PPPOE tunnel route (The wan.X table also gets the route from the ip4table configuration, which is what we actually use for the …
> Mfw 1040 routing fixes

- sync/debian/port_forward_manager.py
I solved this by updating sync-settings port_forward_manager to add DNAT rules for any IP aliases configured on ADDRESSED config type interfaces.
> Add DNAT rules for GUI on interface IP aliases

- sync/openwrt/route_manager.py
Check for ipv6Enabled before writing out 'up' tests
for wans.  Without this check, we might write bogus
interfaces names that cause wan manager to think that
the ipv4 interface is down.
MFW-1051
> route_manager: Check ipv6Enabled for 'up' tests

- sync/openwrt/route_manager.py
In the scripts that manage the default system wan route
we could leave a default-policy.XXXXXX file in tmp in some
cases.  Ensure we always clean it up
MFW-1126
> route_manager: Clean up temp nft rulesets

- sync/openwrt/network_manager.py
For the sake of debuggability, sync the VLAN interface name with
the device name
MFW-1146
> network_manager: Sync vlan device with vlan name

- sync/openwrt/network_manager.py
When adding interfaces to the list of interfaces on a bridge,
ignore disabled interfaces
MFW-1145
> network_manager: Ignore disabled bridged interfaces

- sync/openwrt/network_manager.py
We need to check that the interfaceIds of the interfaces we are
comparing are different, otherwise we are comparing the interface
to itself
MFW-1168
> network_manager: Fix overlapping vlan validation

- sync/openwrt/network_manager.py
This is the value suggested by openwrt documentation for
a "no-settings" connection
MFW-1032
> network_manager: Use 'any' if simApn is None

- sync/openwrt/network_manager.py
Routing is to be decided by the devices WAN routing rules, so add
'route-nopull' to prevent routes being pushed by the server.
MFW-1120
> network_manager: Add route-nopull to openvpn configs

- sync/openwrt/interface_manager.py
Wireguard performance is very sensitive to mtu issues, so do
mss clamping on traffic exiting wireguard interfaces just like
we do for pppoe interfaces
MFW-1244
> interface_manager: Add mss clamping for wg

- sync/debian/wireguard_manager.py
Wireguard is extremely sensitive to MTU issues, so implement mss
clamping for traffic exiting wireguard interfaces
NGFW-13549
> wireguard: Perform mss clamping

- sync/openwrt/network_manager.py
Remove condition that was preventing write_interface_v4_alias from running on DHCP interface types
> MFW-1233-Fix-DHCP-Aliases
